// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQsHMpCdVzJWjIYCbhERd_rxhzAlcnXIk',
    appId: '1:238266545392:web:7ccfaaa42202ea5f93be35',
    messagingSenderId: '238266545392',
    projectId: 'test-211f9',
    authDomain: 'test-211f9.firebaseapp.com',
    storageBucket: 'test-211f9.appspot.com',
    measurementId: 'G-VZ2T8JX4BY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTVLCmxYT3ZHCfDfSOPWXR3T85pzMTbAM',
    appId: '1:238266545392:android:bcafa71586066a6a93be35',
    messagingSenderId: '238266545392',
    projectId: 'test-211f9',
    storageBucket: 'test-211f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_UnW7sbynVrX13aZQrdlJgPadRT4Tc1s',
    appId: '1:238266545392:ios:c40e84948e9e1df093be35',
    messagingSenderId: '238266545392',
    projectId: 'test-211f9',
    storageBucket: 'test-211f9.appspot.com',
    iosBundleId: 'com.example.webrtcTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_UnW7sbynVrX13aZQrdlJgPadRT4Tc1s',
    appId: '1:238266545392:ios:c40e84948e9e1df093be35',
    messagingSenderId: '238266545392',
    projectId: 'test-211f9',
    storageBucket: 'test-211f9.appspot.com',
    iosBundleId: 'com.example.webrtcTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQsHMpCdVzJWjIYCbhERd_rxhzAlcnXIk',
    appId: '1:238266545392:web:6406a430bcdeafb193be35',
    messagingSenderId: '238266545392',
    projectId: 'test-211f9',
    authDomain: 'test-211f9.firebaseapp.com',
    storageBucket: 'test-211f9.appspot.com',
    measurementId: 'G-WMNC3KWMLF',
  );
}
